services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - laravel

  # web:
  #   # image: nginx:alpine
  #   build: 
  #    context: .
  #    dockerfile:  ./nginx/Dockerfile
  #   container_name: laravel_web
  #   volumes:
  #     - .:/var/www
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - app
  #   networks:
  #     - laravel

  # db:
  #   image: mariadb:latest
  #   container_name: laravel_db
  #   environment:
  #     MARIADB_ROOT_PASSWORD: entrename
  #     MARIADB_DATABASE: entrename
  #     MARIADB_USER: prueba
  #     MARIADB_PASSWORD: entrename
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - laravel

networks:
  laravel:
